apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-front
        image: my-wordpress:1.0
        ports:
        - containerPort: 80
